import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { input, confirm } from "@inquirer/prompts";
import { getProjectRoot, getEnvPath } from "./paths.js";
import { logSuccess, logWarning, logInfo } from "../ui/log.js";

const ENV_TEMPLATE = (opts: {
  corpusPath: string;
  neo4jPassword: string;
  apiKey: string;
}) => `# Generated by corpus-intelligence installer
CORPUS_PATH=${opts.corpusPath}

# Neo4j
NEO4J_USER=neo4j
NEO4J_PASSWORD=${opts.neo4jPassword}

# Anthropic
ANTHROPIC_API_KEY=${opts.apiKey}
ANTHROPIC_MODEL=claude-haiku-4-5-20251001

# Embeddings
EMBEDDING_MODEL=all-mpnet-base-v2
EMBEDDING_PROVIDER=sentence_transformers

# Ollama (optional, for local LLM fallback)
OLLAMA_URL=http://host.docker.internal:11434
OLLAMA_MODEL=llama3.1:8b

# Logging
LOG_LEVEL=info
`;

export async function generateEnv(opts: {
  apiKey: string;
  corpusPath?: string;
}): Promise<string> {
  const envPath = getEnvPath();

  if (fs.existsSync(envPath)) {
    const overwrite = await confirm({
      message: `.env already exists. Overwrite?`,
      default: false,
    });
    if (!overwrite) {
      logInfo("Keeping existing .env");
      return envPath;
    }
  }

  const corpusPath =
    opts.corpusPath ||
    (await input({
      message: "Path to your writing corpus:",
      default: path.join(getProjectRoot(), "data"),
      validate: (value) => {
        const resolved = path.resolve(value);
        if (!fs.existsSync(resolved)) {
          return `Directory not found: ${resolved}`;
        }
        return true;
      },
    }));

  const neo4jPassword = crypto.randomBytes(16).toString("hex");

  const content = ENV_TEMPLATE({
    corpusPath: path.resolve(corpusPath),
    neo4jPassword,
    apiKey: opts.apiKey,
  });

  fs.writeFileSync(envPath, content, "utf-8");
  logSuccess(`.env written to ${envPath}`);

  return envPath;
}
